=== Abel2299/2021_LMSGI_ADD/ud04/13/13.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT formulario (datos,carta+,establecimiento)>
<!ATTLIST formulario
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED>

<!ELEMENT datos (nombre,direccion,email,telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT carta (entradaFria,pescados,carnes)*>
<!ELEMENT entradaFria EMPTY>
<!ATTLIST entradaFria
    plato CDATA #REQUIRED>
<!ELEMENT pescados EMPTY>
<!ATTLIST pescados
    plato CDATA #REQUIRED>
<!ELEMENT carnes EMPTY>
<!ATTLIST carnes
    plato CDATA #REQUIRED>
<!ELEMENT establecimiento (instalaciones,calidadComida,atencionPersonal,tiempoRestaurante,espera)>
<!ELEMENT instalaciones EMPTY>
<!ATTLIST instalaciones
    limpieza CDATA #IMPLIED>
<!ELEMENT calidadComida EMPTY>
<!ATTLIST calidadComida
    nota CDATA #REQUIRED>
<!ELEMENT atencionPersonal EMPTY>
<!ATTLIST atencionPersonal
    atencion CDATA #IMPLIED>
<!ELEMENT tiempoRestaurante EMPTY>
<!ELEMENT espera EMPTY>
<!ATTLIST espera
    tiempo CDATA #IMPLIED>

=== Abel2299/2021_LMSGI_ADD/ud04/13/13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formulario SYSTEM '13.dtd'>
<formulario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="13.xsd">
    <datos>
        <nombre>Prueba</nombre>
        <direccion>C/Prueba</direccion>
        <email>prueba@gmail.com</email>
        <telefono>123456789</telefono>
    </datos>
    <carta>
        <entradaFria plato="terrina"/>
        <pescados plato ="bacalao"/>
        <carnes plato="cordero"/>
    </carta>
    <establecimiento>
        <instalaciones limpieza="normal"/>
        <calidadComida nota="7"/>
        <atencionPersonal atencion="satisfactorio"/>
        <tiempoRestaurante></tiempoRestaurante>
        <espera tiempo="3"></espera>
    </establecimiento>
</formulario>

fidsofds
