=== Abel2299/2021_LMSGI_ADD/ud04/EX02_09032021_AbelDominguezDominguez/constelaciones.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/mapaestelar.dtd

-->
<!ELEMENT constelacion (nombreEspañol,superficie,estrellas,objetos,colindantes,observacion)>
<!ATTLIST constelacion
    nombreLatin CDATA #REQUIRED>
<!ATTLIST constelacion
            xsi:noNamespaceSchemaLocation CDATA #IMPLIED
            xmlns:xsi CDATA #IMPLIED>
<!ELEMENT nombreEspañol (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo,masBrillante)>
<!ATTLIST estrellas
    numeroEstrellas CDATA #IMPLIED>
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante
    luminosidad CDATA #IMPLIED>
<!ELEMENT objetos (cumulos,nebulosas,galaxias,cuasares,lluviaMeteoros*)>
<!ELEMENT cumulos EMPTY>
<!ELEMENT nebulosas EMPTY>
<!ELEMENT galaxias EMPTY>
<!ELEMENT cuasares EMPTY>
<!ELEMENT lluviaMeteoros (#PCDATA)>
<!ELEMENT colindantes (nombre)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT observacion (hemisferio,mes,hora)*>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>

=== Abel2299/2021_LMSGI_ADD/ud04/EX02_09032021_AbelDominguezDominguez/constelaciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE constelacion SYSTEM 'constelaciones.dtd'>
<constelacion nombreLatin="Ursa Maior" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="constelaciones.xsd">
    <nombreEspañol>La Osa Mayor</nombreEspañol>
    <superficie>1279.7</superficie>
    <estrellas numeroEstrellas="209">
        <asterismo>7</asterismo>
        <masBrillante luminosidad="108">Alioth</masBrillante>
    </estrellas>
    <objetos>
        <cumulos></cumulos>
        <nebulosas></nebulosas>
        <galaxias></galaxias>
        <cuasares></cuasares>
        <lluviaMeteoros>4</lluviaMeteoros>
    </objetos>
    <colindantes>
        <nombre>Bootes</nombre>
        <nombre>Camelopardalis</nombre>
        <nombre>Canes Venatici</nombre>
        <nombre>Draco</nombre>
        <nombre>Leo</nombre>
        <nombre>Leo Minor</nombre>
        <nombre>Lynx</nombre>
    </colindantes>
    <observacion>
        <hemisferio>Norte</hemisferio>
        <mes>4</mes>
        <hora>21:00:00</hora>
    </observacion>
</constelacion>
