=== Abel2299/2021_LMSGI_ADD/ud04/Pruebas/EjercicioXMLInternet/01.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ATTLIST pedidos
            xsi:noNamespaceSchemaLocation CDATA #IMPLIED
            xmlns:xsi CDATA #IMPLIED>
<!ELEMENT pedidos (pedido*)>
<!ELEMENT pedido (comprador, productos, entrega)>
<!ELEMENT comprador (nombreCliente, apellido1, apellido2)>
<!ATTLIST comprador dni ID #REQUIRED>
<!ELEMENT nombreCliente (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT productos (producto*)>
<!ELEMENT producto (nombrePro, precio)>
<!ATTLIST producto id CDATA #REQUIRED>
<!ELEMENT nombrePro (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT entrega (direcciones)>
<!ATTLIST entrega 
                repartidor (correos|seur) #IMPLIED>
<!ELEMENT direcciones (direccion) >
<!ELEMENT direccion (localidad, provincia)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>

=== Abel2299/2021_LMSGI_ADD/ud04/Pruebas/EjercicioXMLInternet/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM '01.dtd'>

<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="01.xsd">
    <pedido>
        <comprador dni="71041503T">
            <nombreCliente>Juan</nombreCliente>
            <apellido1>Rabano</apellido1>
            <apellido2>Fernandez</apellido2>    
        </comprador>
        <productos>
            <producto id="A2023">
                <nombrePro>Manitou</nombrePro>
                <precio>1</precio>
            </producto>
        </productos>
        <entrega repartidor="correos">
            <direcciones>
                <direccion>
                    <localidad>Aguilar de Tera</localidad>
                    <provincia>Zamora</provincia>
                </direccion>
            </direcciones>
        </entrega>
    </pedido>
</pedidos>
