<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hechos[
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT hechosHistoricos (descripcion, fecha)>
    <!ELEMENT hechos (hechosHistoricos*)>
	<!ATTLIST fecha dia CDATA #REQUIRED >
	<!ATTLIST fecha mes CDATA #REQUIRED >
	<!ATTLIST fecha anyo CDATA #REQUIRED >
   
]>

<hechos>
    <hechosHistoricos>
        <descripcion>youtube</descripcion>
        <fecha dia="15" mes="2" anyo="2005"/>
    </hechosHistoricos>
    <hechosHistoricos>
       <descripcion>google</descripcion>
        <fecha dia="4" mes="9" anyo="1998"/>
    </hechosHistoricos>
    <hechosHistoricos>
        <descripcion>facebook</descripcion>
        <fecha dia="4" mes="9" anyo="2004"/>
    </hechosHistoricos>

</hechos>